#!/bin/bash

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# SYSTEM REPORT SCRIPT
# Author: Muhammad
# Assignment 1: System Report
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Check for required commands before proceeding
for cmd in hostname who uptime lshw df free ip ss ufw; do
    if ! command -v $cmd >/dev/null 2>&1; then
        echo "Error: $cmd is not installed. Exiting..."
        exit 1
    fi
done

# Get system information and save to variables
HOSTNAME=$(hostname)               # System hostname
USERNAME=$(whoami)                 # Current user executing the script
DATETIME=$(date "+%Y-%m-%d %H:%M:%S")  # Current date and time for the report

# OS Information from /etc/os-release
source /etc/os-release
OS="$NAME $VERSION"                # Example: "Ubuntu 20.04 LTS"

# System uptime (how long the system has been running)
UPTIME=$(uptime -p)               # Output like "up 2 hours"

# CPU Information
CPU=$(lshw -class processor | grep -m 1 "product" | cut -d: -f2 | sed 's/^ *//g')

# RAM Size
RAM=$(free -h | awk '/^Mem/ {print $2}')  # Example: "8.0G"

# Disk(s) Information
DISKS=$(lshw -class disk | grep -E "product|size" | awk -F: '{gsub(/^ +| +$/, "", $2); printf "%s ", $2; if(NR % 2 == 0) print "";}' )

# Video Card Information
VIDEO=$(lshw -class display | grep "product" | cut -d: -f2 | sed 's/^ *//g')

# Network Information (Host Address, Gateway, DNS)
DEFAULT_INTERFACE=$(ip route | awk '/default/ {print $5}')
HOST_ADDRESS=$(ip -4 addr show "$DEFAULT_INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
GATEWAY_IP=$(ip route | awk '/default/ {print $3}')
DNS_SERVER=$(grep -m1 "nameserver" /etc/resolv.conf | awk '{print $2}')

# System Status (Users, Disk Space, Processes, Load, Ports, UFW)
LOGGED_USERS=$(who | awk '{print $1}' | sort -u | paste -sd,)
DISK_SPACE=$(df -h --output=target,avail | tail -n +2 | awk '{printf "%s %s\n", $1, $2}')
PROCESS_COUNT=$(ps -e --no-headers | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average: ' '{print $2}')
LISTENING_PORTS=$(ss -tuln | awk '/LISTEN/ {split($5,a,":"); print a[length(a)]}' | sort -n | uniq | paste -sd, -)
UFW_STATUS=$(sudo ufw status | head -n 1)

# ==========================================
# OUTPUT REPORT: Display the collected data
# ==========================================
echo
cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS
EOF
echo
